#! /bin/sh
#
# Copyright (c) 2015, Peter Piwowarski
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer. 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# envvar THRESH
#
# The average line length in characters at which we start debreaking lines.
# Not all files are alike, yours may need downward revision.
THRESH=${THRESH:-"60"}

# envvar EOL
#
# Internal end-of-line marker, pick a string your file won't have
EOL="##!!EOL!!##"

# real endline
ENDL="
"

# paragraph control
PARA=""
NUMLINES=$((1))  #
CHARCOUNT=$((0)) # accumulators

while IFS= read -r LINE
do
	if [ -z "$LINE" ]
	then
		# Output as one line if its average line length indicates a
		# real paragraph
		if [ $(($CHARCOUNT / $NUMLINES)) -gt $THRESH ]
		then
			printf "%s\n\n"\
				"$(printf "%s" "$PARA" | sed "s|$EOL| |g")"
		else
			# Output as multiple lines otherwise
			env IFS=$ENDL printf "%s\n\n"\
				"$(printf "%s" "$PARA" | sed "s|$EOL|\\$ENDL|g")"
		fi

		# "Eject" the paragraph
		PARA=
		NUMLINES=$((1))
		CHARCOUNT=$((0))
	else
		PARA="${PARA}${LINE}${EOL}"

		# accumulate
		NUMLINES=$(( $NUMLINES + 1))
		CHARCOUNT=$(( $CHARCOUNT + $(printf "%s" "$LINE" | wc -c) ))
	fi
done
